spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:mysql://localhost:3306/emotionbank?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100

server:
  port: 8080


logging:
  level:
    org:
      hibernate:sql: DEBUG
      springframework:
        security: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  access-token-header: Authorization
  refresh-token-header: Authorization-refresh
  access-token-expiration-time: 600000
  refresh-token-expiration-time: 1209600000

redis:
  host: redis
  port: 6379
  password: password