spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:mysql://localhost:3306/emotionbank?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100

redis:
  host: redis
  port: 6379
  password: password

server:
  port: 8080

social:
  context-type: application/x-www-form-urlencoded;charset=utf-8

redirect-uri: "http://localhost:8080/auth/login/"

kakao:
  client:
    id: client-id
    secret: client-secret

logging:
  level:
    org:
      hibernate:sql: DEBUG
      springframework:
        security: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  access-token-header: Authorization
  refresh-token-header: Authorization-refresh
  access-token-expiration-time: 600000
  refresh-token-expiration-time: 1209600000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
