version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root123!
      MYSQL_DATABASE: emotionbank
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:7.2-rc3
    ports:
      - "6379:6379"
    command: redis-server --requirepass password