version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emotionbank
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - C:/mysql/data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7.2-rc3
    ports:
      - "6379:6379"
    command: redis-server --requirepass password